### ISSUE TITLE
Use PEP 484-style function annotations for typing information

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-python#101]
[PEP 484](https://www.python.org/dev/peps/pep-0484/) has been provisionally adopted to create a standard method of using function annotations to provide type hints for function parameters and return values. We may want to consider using these at some point instead of (or in addition to, though it would be redundant) specifying types in the docstring. A real-world example of (incomplete) usage is the [Flow module of the MediaWiki bot framework Pywikibot](https://github.com/wikimedia/pywikibot/blob/master/pywikibot/flow.py), which I helped write years ago (though the annotations were not my work).

**Comment by VisLab** [comment]
We are going to use docstrings at least for now.  It is possible to get tool to convert later.
