### ISSUE TITLE
Check that # can only be used as a placeholder.

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#102]
Special characters such as # should not be allowed in descriptions. Check to see what other characters are not allowed and make sure that it agrees with the spec.

**Comment by VisLab** [comment]
The requirements of characters have now been expanded in the draft HED 3 specification:

"In HED strings, # term placeholders represent user-supplied values. In addition to alphanumeric characters, they may contain +, -, and ^ (addition, subtraction, exponentiation), : (clock times), $ (currency) and periods (decimal points). These values may not contain other punctuation. A limited number of special Unicode characters may be allowed if explicitly specified in the HED schema."

The value parameters in HED spreadsheets and dictionaries can follow these rules.   There should also be a well-defined place in the validator where this is checked so that if it needs to be changed in the future it will be easier to find. Test cases need to be included.

**Comment by IanCa** [comment]
https://github.com/hed-standard/hed-python/pull/231

This behavior will probably still need refinement, but this will make HedValidator by default reject placeholders.  It will still however check units on them and issue appropriate errors

eg if you don't set it to allow placeholder mode 
"Duration/# hz" will report an error for the placeholder character being invalid, but also a second for wrong units
