### ISSUE TITLE
hed_cache HED_VERSION_EXPRESSION needs to be fixed

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#110]
Currently HED_VERSION_EXPRESSION is r'HED(\d+.\d+.\d+)'

This needs to be expanded to include HEDx.x.x-alpha.x. There are two official versions 

https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string. The first seems to be the one we want:

^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$

Here is the test site:
https://regex101.com/r/Ly7O1x/3/

**Comment by IanCa** [comment]
https://github.com/hed-standard/hed-python/pull/111
