### ISSUE TITLE
Rename some methods

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-python#12]
The methods `TagValidator.tag_is_valid()` and `HedDictionary._string_list_2_lowercase_dictionary()` should be renamed. In the JavaScript version, the first one was renamed to (converting to underscores) `tag_exists_in_schema()`, and the latter was renamed to (in JS camelCase) `stringListToLowercaseDictionary()`.

**Comment by dungscout96** [comment]
This won't be an issue for HEDTools' call to the validator
