### ISSUE TITLE
Implement tool to check schema nodes and descriptions are compliant

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#121]
Because library schema are now being developed, we need to implement support for checking format.  This is to help schema designers design compliant schema. The spec says the following:

"HED 3G schema terms or nodes (e.g., Sensory-event) can only contain alphabetic characters and hyphen characters. They cannot have white space. The first letter of a term should be capitalized for readability; the remaining characters should be lowercase. Beginning with third generation HED (HED schema versions 8.0.0 and later), terms in a given schema must be unique within that schema. This uniqueness rule allows automated expansion of short form HED strings into their full long forms.

A description contained in trailing square brackets can be used to indicate the purpose of the tag in event annotation. To ease automated interpretation, such schema descriptions in square brackets must only contain alphanumeric characters, blanks, hyphens, underbars, colons, semicolons, and periods. They must not contain other punctuation, parentheses, brackets, or braces."

**Comment by VisLab** [comment]
Here is a start on the rules and recommendations for HED schema. Recommendations generate warnings if violated.

Requirements:

    Node names should start with an upper case letter or a number.
    Node names should not contain blanks.
    Node names can only contain letters, numbers, hyphens. They cannot contain any other symbols or punctuation.

Recommendations:

    Recommend short names (give a warning if longer than 30 characters).

**Comment by IanCa** [comment]
This is done, but we do not have the warning for long term names(and it's not listed in the spec)
