### ISSUE TITLE
delete_file_if_it_exist   crashes on None argument

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#122]
delete_file_if_it_exist   in hedtools file_util.py crashes when None is passed as the filename.  An empty string works, but None should work too,

Also refactor to rename to delete_file_if_it_exists.

**Comment by VisLab** [comment]
Also include tests in the unit tests for both an empty string, a None, or various real names that don't exist.

**Comment by IanCa** [comment]
https://github.com/hed-standard/hed-python/pull/152
