### ISSUE TITLE
HED schema doesn't correctly convert multiple values of attributes

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#143]
When a node has multiple values of the same attribute, the wiki2xml doesn't seem to be converting correctly:

** Famous <nowiki>{relatedTag=Familiar, relatedTag=Unfamiliar}[Something known by many people but necessarily because of direct contact.]</nowiki>

Only keeps one relatedTag.  This probably needs to be fixed as soon as possible.

**Comment by VisLab** [comment]
If it already takes an alternative syntax like:

{relatedTag=Familiar,Unfamiliar}   

that would be okay.  I just need to document it in the specification.  Thx

**Comment by IanCa** [comment]
This is now handled.

wiki lists all values as separate entries with repeated labels
xml lists the values comma separated strings, with just one label
