### ISSUE TITLE
JSON format for API calls with HEDTools and CTAGGER

### ISSUE THREAD

**Issue by dungscout96** [hed-standard/hed-python#145]
This is a proposal for the format of the JSON string to be sent from MATLAB HEDTools and CTAGGER and of the report back from the Python validator.

**To Python validator**
```
{
    "HEDVersion": string,
    "check_for_warnings": bool,
    "run_semantic_validation": bool,
    "annotation": string, Array, or Object 
}
```
* In the past HEDTools sends the whole HED schema XML file to the validator. We might not want people to create new schema on the fly but rather extend the schema only where extensionAllowed and encourage them to bring any suggestions for officially extending the base schema to hed-specification repo. Thus only HEDVersion number is needed.
* Value of `annotation` can be a single HED string, an Array of HED strings, or an Object with the same format as the BIDS _events.json file with only `HED` key. An example Object: 
```
{
    "<some_categorical_field>": {
        "HED": {
            "<code1>": "HED string of code1",
            "<code2>": "HED string of code2"
        }
     },
    "<some_value_field>": {
        "HED": "HED string of value field"
    }
}
``` 

**Report back from the validator**
```
{
    "issues": Array,
    "warnings": Array
}
```
Value of "issues" or "warnings" can be an empty array (no issues/warnings), an array of strings, array of arrays, or array of objects.
- If HEDTools sends a single HED string to validate, Array value will be an array of issue strings.
- If HEDTools sends an array of HED strings, Array value will be an array of arrays of issue strings.
- If HEDTools sends an Object, Array value will be an array of objects with format
```
{
    "categorical_field": {
        "code1": Array
        "code2": Array
    }
}
```
or
```
{
    "value_field": {
        "hed_string": Array
    }
}
```
where each array is an Array of issue strings.

**Comment by VisLab** [comment]
A new format for the call and return of web services for HED  has been implemented and is now online.  This has been completed. @dungscout96
