### ISSUE TITLE
Validator allows unit modifiers on non-SI units

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-python#177]
The code in this validator, which was translated from the JavaScript version, erroneously passes non-SI units which contain SI unit modifiers, such as "millihour" and "Gft". The JavaScript version was patched in https://github.com/hed-standard/hed-javascript/commit/1929d981e69d6676890aab6b6655d5622f565256, and a similar fix should be applied here.

**Comment by IanCa** [comment]
In the new pull request

**Comment by VisLab** [comment]
This has been fixed.
