### ISSUE TITLE
Validator is not detecting duplicate tags

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#189]
The HED validator is not correctly detecting duplicate tags that are extensions.  

**Example:**  `Attribute/Red` has no validation errors.  Short-to-long conversion correctly detects the error:

> Unable to convert HED string:
> ERROR: 'Red' appears as 'Attribute/Sensory/Visual/Color/CSS-color/Red-color/Red' and cannot be used as an extension.  10, 13

Here is how I think this should be handled on validation.  

1.   **No duplicate tags should ever allowed as extensions regardless of HED version**.  HED-2G and HED-3G both have `Red` in their hierarchy so  `Attribute/Red`  would always be an error regardless of HED version.
2.   Tag extensions would always generate a warning, so `Attribute/Bananas` would always generate a warning regardless of the version since `Bananas` is a tag extension.

I think that putting in the restriction that tag extensions can't be in the hierarchy already simplifies the logic.
@IanCa  @happy5214

**Comment by IanCa** [comment]
#1. Should now be fixed with the new pull request.
#2. Is not yet handled.

**Comment by IanCa** [comment]
This should be resolved as of a while ago.
