### ISSUE TITLE
Basic usage example for python validator

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#23]
There are some usage cases for the python validator buried in the repo:

https://github.com/VisLab/HEDTools/tree/master/python/hedvalidation/examples

It would be nice to have a very concise and basic usage example in the primary README for python (and probably for the other programming languages as well). This would include installation, and applying the validator to a file that has an HED tag column.

**Comment by dungscout96** [comment]
The example link seems to be broken

**Comment by happy5214** [comment]
https://github.com/hed-standard/hed-python/tree/master/hedvalidation/examples should be the correct link.

**Comment by VisLab** [comment]
Fixed data files and updated with latest merge.
