### ISSUE TITLE
Create new property type for unit attributes

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-python#230]
Currently, `unitClassProperty` encompasses both unit class attributes (`allowedCharacter` and `defaultUnits`) and unit attributes (`SIUnit` and `unitSymbol`). This is needlessly confusing, and I'm proposing that a new `unitProperty` type be created for the latter category. https://github.com/hed-standard/hed-javascript/pull/25 depends on this change, and not making this change will require hardcoding the attributes in the respective categories, which will fail if library schemas introduce any additional attributes in these categories.

**Comment by IanCa** [comment]
https://github.com/hed-standard/hed-python/pull/233

Note any previous schemas with attribute sections will not work after this update until you update the UnitSymbol and SIUnit attributes to be unitProperty.

**Comment by VisLab** [comment]
This has been incorporated in the HED-3G schema.
