### ISSUE TITLE
Remove support for the default property, include support for defaultUnits

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#234]
The `default` attribute should be ignored going forward.  It is not present in HED-3G.  It's original specification would require that default units (not the ones associated with the `unitClass` but with the tag itself) would automatically be added when the HED string is expanded.

I am not sure that we actually have any support for adding `defaultUnits` when a tag is expanded.  Could @IanCa check and respond to the issue so we can discuss what to do.

**Comment by IanCa** [comment]
The only handling of default that still exists is to convert it to DefaultUnits if found on units in the older xml.  The older support for 'default' on tags was removed entirely.

So I think this is already done.
