### ISSUE TITLE
Wiki loader doesn't flag erroneous line breaks

### ISSUE THREAD

**Issue by IanCa** [hed-standard/hed-python#237]
The following example should produce some kind of warning or error about the extra line break.  Currently it fails to load properly and produces weird results.

** Parameter <nowiki>[Any factor that defines a system and determines or limits its performance. A variable whose value changes the characteristics of a system or a function.
]</nowiki>
*** <nowiki># {takesValue}</nowiki>

**Comment by VisLab** [comment]
Could we verify that this has been handled with the new Schema.

**Comment by VisLab** [comment]
Fixed.
