### ISSUE TITLE
Need to validate definition tags found in BaseInput

### ISSUE THREAD

**Issue by IanCa** [hed-standard/hed-python#254]
Right now it extracts all the definitions but never validates them when they're in a BaseInput class.  It only validates definition issues, not general invalid tag and such issues.

Probably should add a validate definitions call on DefDict for this.

**Comment by IanCa** [comment]
I'll need to investigate this slightly more next week, but I believe they are being validated currently as part of the general file validate pass.

**Comment by VisLab** [comment]
The validator validates definitions in place and then removes them.  This has been handled.
