### ISSUE TITLE
Deadlink on website

### ISSUE THREAD

**Issue by antotorov** [hed-standard/hed-python#26]
Hello,
I am posting this here although this is an issue related to the [hed website](http://www.hedtags.org/hed-docs/).
Clicking on "HED validator" on this page leads to [this internal server error page](http://visual.cs.utsa.edu/hed/validation).
Thanks for this work, I just discovered it and will most probably use it in my BIDS data sets (working in fMRI mostly).
Best
A

**Comment by dungscout96** [comment]
The webpage is back up. Thank you for pointing it out to us.
