### ISSUE TITLE
online HED validator is not picking up versions of the HED schema

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#28]
Online validator seems to be failing.  The pull down for the HED xml no longer lists options. When I try to validate any file it just says spreadsheet could not be processed.

**Comment by VisLab** [comment]
From Ian:
_Visualtest should be working now.  I'm still trying to figure out what changed to break it, so this is just a manually deployed temp one.  The issue is it doesn't have the .xml files in the right place.

Only the latest xml works.  Earlier ones are crashing in something to do with the unit code right now, getting a KeyError on "defaultUnits" among other things.  Should < 7.1 still work, or is it expected to be broken?_

It should work on all versions.   The validator was recently changed to handle all versions.  Do you know what commit the current web deployment is using and where it expects to get the xml from?

Thanks

**Comment by IanCa** [comment]
The xml is currently expected to be in the hedvalidation/hed folder.  I thought I had changed it to use the one from hed-specification, I'm looking into why it doesn't seem to be anymore.  I plan to make it get the schema from hed-specification, unless it should be getting them from somewhere else.

What's on visiualtest right now is the latest commit from master, and I copied in the XML from the latest commit of hed-specification master.

VIsual is still set to auto update each night(with the broken one).  Visualtest is the one that should work, I disabled auto update until I've fixed it.

**Comment by VisLab** [comment]
It should go to hed-specification.  Unfortunately visual is the one that is
public facing and has the links from the various websites.  We'll need to
get that one up.  Thanks for working on it.

**Comment by IanCa** [comment]
okay both should be working now, visualtest is set to auto update each night.  Visual is frozen.

XML version numbers under 7.1 do not work.

**Comment by happy5214** [comment]
#31 should fix it for 7.1.0, and I think #22 will fix it for 7.1.1.

**Comment by VisLab** [comment]
Fixed in pull request #22
