### ISSUE TITLE
Verify tag extension warning still being produced.

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#281]
Agent-property/Agent-task-role/Experimental-participant doesn't generate a warning on the web version of the validator, although the last term should be Experiment-participant.

Issue might be that hedtools is not generating the extension warning anymore after the latest refactoring or webtools is not handling warnings correctly.

**Comment by IanCa** [comment]
Check for warnings is not being set in the EventValidator constructor inside the function:
string_validate(hed_schema, string_list):
in strings.py

As far as I can tell the extended tag is still detected otherwise.

**Comment by VisLab** [comment]
This warning needs to be verified or corrected and the issue closed.  @IanCa

**Comment by IanCa** [comment]
This is an issue in webtools code.  You need to create the HedValidator with check_for_warnings=True.(or we can make that the default setting if you prefer)
