### ISSUE TITLE
Pass through error messages in reporter

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#283]
It would be good to update the error messages to make it easier to find the error in the file.  

The following JSON file error:
cannotParseJson: [Expecting ',' delimiter: line 128 column 4 (char 9377)]
is the result of a missing comma at the end of the line.  It would be nice to print out the beginning of the line as part of the error message.

Another item that throws an exception is the result of having the word "don't" in a Description. It gives the following error:

UnicodeDecodeError: ['ascii' codec can't decode byte 0xe2 in position 7593: ordinal not in range(128)]

Again, it would be nice to print up to the and around the error to make it easier to find in the file.

**Comment by IanCa** [comment]
For 1, there's nothing to address.  This is the error produced by the json parser, it doesn't provide any further data.  We would need to use a different library or similar to get any further specific data.

For 2, we automatically ignore any invalid characters in wiki files with the errors='replace' command.

**Comment by VisLab** [comment]
JSON and XML errors are generated by libraries.  This will be deferred as a long term task to make more usable.

**Comment by VisLab** [comment]
@IanCa can this issue be closed?

**Comment by IanCa** [comment]
It should still be as before, with invalid characters being replaced.

eg the don't above produces: [{'code': 'SCHEMA_CHARACTER_INVALID', 'message': "Invalid character ''' in desc for 'Item/Sound/Musical-sound/Instrument-sound/Violin-sound/Violin-subsound2' at position 3.  'don't", 'severity': 10}]

There is nothing to address for json etc parsing errors.(they should be using proper tools for that)

**Comment by VisLab** [comment]
We decided not to address this.
