### ISSUE TITLE
Delimiter validation updates from JavaScript version

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-python#3]
The Python code includes `TagValidator.comma_is_missing_before_opening_bracket()`, which is never true in the context in which it is called. The comma validation function `TagValidator.find_comma_issues_in_hed_string()` also does not flag errors for extra commas or tildes in illegal contexts (e.g. `,,` or `,~`). I've fixed both in the JavaScript version.

**Comment by happy5214** [comment]
This expanded delimiter validation is implemented in the function `findDelimiterIssuesInHedString` in https://github.com/VisLab/HEDBidsValid/blob/semantic/validators/hed.js. Some tests can be found in https://github.com/VisLab/HEDBidsValid/blob/semantic/tests/hed.spec.js, with the block starting with `it('should not have malformed delimiters', function() {`.

The error message now includes the illegal delimiter and the character index of that delimiter in the HED string. The error message is listed as `extraDelimiter` in https://github.com/VisLab/HEDBidsValid/blob/semantic/utils/issues.js.

**Comment by owinterbg** [comment]
This issue was addressed in commit 134be8c037f4fb23003efc22b8b9ee04013311a2
