### ISSUE TITLE
Handling of failure to load a schema

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#333]
We have a new error code to cover the case where the schema file could not be accessed or contained invalid XML and could not have first level parsing.  We need to check to make sure the Python code detects that error and uses the correct issue. 

**HED_SCHEMA_LOAD_FAILED:** Unable to load a schema.
 ~ The schema file is inaccessible.
 ~ The schema file does not contain valid XML.

**Comment by IanCa** [comment]
These are currently thrown as HedFileError(as are a variety of similar errors, such as a media wiki file with sections out of order).  You can't create the schema object at all, so there's no way this would show up as an issue.

We would need to re-write things to allow you to create an invalid schema object if we want this.

**Comment by VisLab** [comment]
The HedFileError now includes and issue list of tuples.  This is handled, although it may need to be revisited.
