### ISSUE TITLE
Def-expand not in its own tag group

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#334]
When definitions are expanded, the Def-expand tag should be in its own tag group that includes the definition's value:

(Def-expand/play-movie, (xxxxx))

The Def-expand doesn't seem to be in any tag group when definitions are expanded during assembly.

**Comment by IanCa** [comment]
Verified there's an issue with processing base file input with an operation(eg expanding def tags)

Fix will be in later today...

**Comment by VisLab** [comment]
Validates all of the columns and changes the columns (such as removes definitions) before assembling and validating rows.  This could be checked further, but is basically handled.
