### ISSUE TITLE
Remove arbitrary leaf extensions

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-python#5]
In previous versions of the HED schema, extensions were allowed from any leaf node, regardless of whether or not there is an `extensionAllowed` attribute on that node's path. Now, this is being phased out in favor of requiring this attribute somewhere in a node's path in order for the extension to be legal. In particular, the leaf extension code should be removed from `TagValidator`, including the `_leaf_extensions` field and the `is_leaf_extension_allowed_tag` method. The `leafExtension` error type should also be removed.

There is a [branch](https://github.com/hed-standard/hed-python/tree/develop) with these changes.

**Comment by owinterbg** [comment]
As far as I can see theses issues are no longer relevant to the current version of the validator.
