### ISSUE TITLE
Annotations validated although prefix for the library schema is missing

### ISSUE THREAD

**Issue by tpatpa** [hed-standard/hed-python#501]
When using the [jupyter notebook](https://github.com/hed-standard/hed-examples/blob/main/hedcode/jupyter_notebooks/bids_processing/bids_validate_dataset_with_libraries.ipynb) to validate [sub-ieegModulator](https://github.com/tpatpa/bids-examples/tree/master/xeeg_hed_score/sub-ieegModulator) annotations, the notebook returns 'No HED validation errors' although prefix ('sc') for the library schema is missing.

For this subject, annotations were made [using the HED column](https://bids-specification.readthedocs.io/en/stable/99-appendices/03-hed.html#annotation-using-the-hed-column).

Full WIP bids example dataset [here](https://github.com/tpatpa/bids-examples/tree/master/xeeg_hed_score).

**Comment by VisLab** [comment]
This is fixed in hedtools-0.1.0 which has been released on PyPI.
