### ISSUE TITLE
Need more generalized schema loading

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#525]
With the HED now supporting library schema and in conjunction with the pending BIDS specification for HEDVersion.

Here are versions that should be parsed:

"8.0.1"
"score_0.0.1"
"ts:8.0.1"
"sc:score_0.0.1"

Each of the above as a single item in a list.

["8.0.1", "sc:score_0.0.1", "ts:8.0.1"]

"https://github.com/hed-standard/hed-specification/hedxml/hed8.0.0.xml"

"sc:filename.xml"

"sc:https://github.com/hed-standard/hed-specification/hedxml/hed8.0.0.xml"

See the new specification for BIDS URIs:
[https://github.com/bids-standard/bids-specification/pull/918](https://github.com/bids-standard/bids-specification/pull/918)

"sc:bids::myfile.xml"

**Comment by IanCa** [comment]
This is in aside from the directly loading from url/file notation.  That didn't make sense in our setup at the time, but could be revisited in the future.

**Comment by VisLab** [comment]
Closed for now.... may be revisited in the future.
