### ISSUE TITLE
Webtools remap after split_events sets value of duration column new events to n/a

### ISSUE THREAD

**Issue by monique2208** [hed-standard/hed-python#559]
When running remap after split_events. The events that were newly created by split events, have their duration column set to n/a. 

Remap alone causes no issues, and other operations (delete_columns, rename_columns) do not make changes to the new event durations.

Original event file, remodel json, and outcome event file is appended.
[events_remodeljson_outputfile.zip](https://github.com/hed-standard/hed-python/files/10084541/events_remodeljson_outputfile.zip)

**Comment by VisLab** [comment]
Corrected in HEDTools [version: 0.1.0+171.geb7d925 date: 2022-12-22T09:32:14-0600] on develop branch.

Latest versions on hed-python/develop should now work.
