### ISSUE TITLE
Remodeler returns nan instead of n/a

### ISSUE THREAD

**Issue by monique2208** [hed-standard/hed-python#563]
Currently the Remodeler returns column values set to n/a as nan. Values seem to be correctly set to n/a when they have been changed by the Remodeler.

Example:

```
onset	duration	trial_type	accuracy	response_time	A_stim	B_stim	fixation_color	event_type
0.0	4.0	1	1	1.624	flirk.wav	slirk.wav	n/a	n/a
0.0	0.8	1	nan	nan	flirk.wav	nan	n/a	first_stim_nonword
1.0	0.8	1	nan	nan	nan	slirk.wav	n/a	second_stim_nonword
1.8	2.2	1	nan	nan	nan	nan	red	fixation
2.624	0.0	1	1	nan	nan	nan	n/a	response
4.017000000000003	4.4	2	0	1.652	creath.wav	steath.wav	n/a	n/a
4.017000000000003	0.8	2	nan	nan	creath.wav	nan	n/a	first_stim_nonword
5.017000000000003	0.8	2	nan	nan	nan	steath.wav	n/a	second_stim_nonword
5.817000000000003	2.6000000000000005	2	nan	nan	nan	nan	red	fixation
6.669000000000003	0.0	2	0	nan	nan	nan	n/a	response
...
```

Columns fixation_color and event_type were added by the Remodeler.

**Comment by VisLab** [comment]
@monique2208

Could you please retest using:
- The [https://hedtools.ucsd.edu/hed_dev](https://hedtools.ucsd.edu/hed_dev) online tools.
- The current version of hed-python develop branch.

Make sure that this has been corrected in both cases.

**Comment by monique2208** [comment]
The issue has been corrected in current hed-python develop branch and hedtools.
