### ISSUE TITLE
Not listed tasks are reset to original

### ISSUE THREAD

**Issue by monique2208** [hed-standard/hed-python#567]
When only running the remodeler for a specific task, the other event files are returned to their original state. 

I wanted to run different remodel transformations for different tasks. There are no problems with the first task, but when I run the next the remodeler resets the first one I did back to the backed up version. 

When I specify which task to run the remodeler on I think the event files belonging to other tasks should not be touched.

**Comment by VisLab** [comment]
Fixed in PR #571
