### ISSUE TITLE
And and Or will be valid tags in HED 8.2.0

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#620]
The query format using And and Or will probably need quotes.  @IanCa what do you suggest?

**Comment by IanCa** [comment]
I have no concerns about changing them, it'll be trivial in code.  || and && would be the most obvious replacement to me.

Also note "," and "and" are exactly equivalent currently.  So we only strictly need a replacement for or.  Aliases are trivial to add with how it's setup.

eg "A and B and C" vs "A, B, C" vs "A, B and C" are all exactly equal currently.

**Comment by VisLab** [comment]
@IanCa I think we need to make the change to || and && as And and Or are HED tags in 8.2.0.  Would this be hard to do before release --- let me know and includes some tests.

**Comment by IanCa** [comment]
https://github.com/hed-standard/hed-python/pull/951

Let me know if you have any issues.  Comma as 'and' is still supported as well.
