### ISSUE TITLE
Move invalid character checks to HedStringDelimiter

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-python#74]
`HedStringDelimiter` should check for invalid characters (currently curly braces and square brackets) before invalid strings reach tag validation. The invalid character tests also need to be moved to the corresponding test module.

**Comment by happy5214** [comment]
Now that `HedStringDelimiter` is clearly a utility class, is it even desirable to have validation checks in it?

**Comment by VisLab** [comment]
We will revisit this. However, right now we are focused on separating the
file I/O part of it.   The validator will need to be restructured when we
go do dataset level validation.

**Comment by IanCa** [comment]
These are still handled in 
TagValidator.find_invalid_character_issues

It doesn't seem like we want to change it at this time.
