### ISSUE TITLE
Basic non-semantic tag test improvements from JavaScript

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-python#8]
Here are some of the test differences I found between the Python and JavaScript versions. This issue contains basic non-semantic checks.

All of these tests are in `test_tag_validator.py` unless otherwise noted.

- Check for legal duplicate tags in `test_check_if_duplicate_tags_exist()`, as in [this JS code](https://github.com/VisLab/HEDBidsValid/blob/379fb125028baf3cecfc49989308581d432c646c/tests/hed.spec.js#L621).
- Pass both the original and formatted tags in `check_capitalization test()`.

**Comment by owinterbg** [comment]
updated versions of these test are located in test_translation_hed.py
