### ISSUE TITLE
defusedxml.lxml deprecated

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-python#80]
The `defusedxml.lxml` parsing library used by the code is deprecated and may be removed in a future release. We should find a replacement. See https://pypi.org/project/defusedxml/#defusedxml-lxml.

**Comment by VisLab** [comment]
Does this mean that we don't need it anymore?   If we don't need it, can you remove.  Also, Ian mentioned that we probably need to switch to openpyxl for other parsing needs.  Do you know how this library relates to lxml and difusedxml?

**Comment by happy5214** [comment]
This deprecated library was used again in `schema_node_map.py`, a brand-new module. We really need to replace this.

**Comment by VisLab** [comment]
What is the suggested replacement?

**Comment by happy5214** [comment]
`defusedxml` comes with an `ElementTree` implementation that wraps around the module of the same name in `xml.etree`, which is used elsewhere in the code, so we could use that.

**Comment by VisLab** [comment]
Note: we're going to need to address this.....

hed\util\hed_dictionary.py:10: DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.
  from defusedxml.lxml import parse
xlrd\xlsx.py:266: PendingDeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.
for elem in self.tree.iter() if Element_has_iter else self.tree.getiterator():
xlrd\xlsx.py:312: PendingDeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.
  for elem in self.tree.iter() if Element_has_iter else self.tree.getiterator():

**Comment by IanCa** [comment]
Where are you seeing those warnings?

Here's a draft with the lxml references removed.
https://github.com/hed-standard/hed-python/pull/117
