### ISSUE TITLE
deprecatedFrom shouldn't give a warning for self

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#814]
In addition to valid schema values in the `deprecatedFrom`, the schema validator should not give a warning when the version is itself. Otherwise the prerelease will always give a warning when we add this tag.

**Comment by VisLab** [comment]
@IanCa It turns out that the HED specification for deprecatedFrom states:

>This element is deprecated. The value of the attribute is the latest schema version in which the element appeared before it was deprecated..

This means that it should give an error when the version is itself.  Could you undo the change in a PR and mention this issue?

**Comment by IanCa** [comment]
https://github.com/hed-standard/hed-python/pull/869
