### ISSUE TITLE
We must start sorting event times before checking onsets and offsets

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#843]
@IanCa @happy5214 @dungscout96:  It turns out BIDS events files are not required to have their times sorted in ascending order. Consequently, the HED validator should include a warning when the times are not sorted and must sort before checking onsets and offsets.

See [BIDS spec issue #1691](https://github.com/bids-standard/bids-specification/issues/1691).

**Comment by IanCa** [comment]
Is the goal to support out of order tags in general, or just for validation?

This could fairly easily be rolled into the "combine multiple lines with the same timestamp" code, where BaseInput.series_filtered could return them sorted, not just combined.

**Comment by VisLab** [comment]
Yes sounds good.

**Comment by VisLab** [comment]
For validation sorting is done prior to validation.  For analysis -- such as with EventManager -- unsorted onsets result in error -- we require sorting before analysis.
