### ISSUE TITLE
Unit and value test improvements from JavaScript

### ISSUE THREAD

**Issue by happy5214** [hed-standard/hed-python#9]
Here are some of the test differences I found between the Python and JavaScript versions. This issue contains unit and value checks.

All of these tests are in `test_tag_validator.py` unless otherwise noted.

- Check a unit-less value in `test_get_unit_class_default_unit()`, as in [this JS code](https://github.com/VisLab/HEDBidsValid/blob/379fb125028baf3cecfc49989308581d432c646c/utils/__tests__/hed.spec.js#L192).
- Check tags with multiple unit classes in `test_get_unit_class_units()`, as in [this JS code](https://github.com/VisLab/HEDBidsValid/blob/379fb125028baf3cecfc49989308581d432c646c/utils/__tests__/hed.spec.js#L256).
- Check a value-taking tag with no unit class in `test_is_unit_class_tag()`, as in [this JS code](https://github.com/VisLab/HEDBidsValid/blob/379fb125028baf3cecfc49989308581d432c646c/utils/__tests__/hed.spec.js#L159).
- Check a non-numeric tag in `test_is_numeric_tag()`, though I don't see a use for `TagValidator.is_numeric_tag()` apart from this test. It is not in the JS code.
- Check tags with replacement pounds in `tag_takes_value()`, as in [this JS code](https://github.com/VisLab/HEDBidsValid/blob/379fb125028baf3cecfc49989308581d432c646c/utils/__tests__/hed.spec.js#L138).
- Check a value-taking tag in `test_is_extension_allowed_tag()`, as in [this JS code](https://github.com/VisLab/HEDBidsValid/blob/379fb125028baf3cecfc49989308581d432c646c/utils/__tests__/hed.spec.js#L305).
- Check a time in HH:MM format in `test_check_if_tag_unit_class_units_exist()`, as in [this JS code](https://github.com/VisLab/HEDBidsValid/blob/379fb125028baf3cecfc49989308581d432c646c/tests/hed.spec.js#L480).

**Comment by VisLab** [comment]
Please got through each test case above and determine:
1)  Is it covered by the new test cases?  if so eliminate
2)  If it is not covered by the new test cases is this something we need to test for?  If yes, write a "new" test case.
3)  If anything is left eliminate.
