### ISSUE TITLE
mediawiki to xml fails when {} used for description

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-python#99]
If the mediawiki has an element where the description is in curly braces instead of square brackets, the whole thing fails and no appropriate error message is produced as output.  Log files say it failed, but don't produce a line number with error.

In order to find the issue, I had to keep taking things out of the mediawiki until it passed to narrow down the problem.

**Comment by IanCa** [comment]
https://github.com/hed-standard/hed-python/pull/116
